schemes = "https://github.com/Softsun2/base16-schemes-source"
# templates = "my-templates"

[[extra_scheme]]
name = "tarko"
source = "https://github.com/Softsun2/base16-tarko-scheme"

[[extra_scheme]]
name = "og-themes"
source = "https://github.com/Softsun2/base16-og-themes"

[[extra_template]]
name = "dwm-xrdb"
source = "https://github.com/Softsun2/base16-dwm-xrdb"

# kitty
[[item]]
file = '$HOME/.dotfiles/theme/kitty/theme.conf'
template = 'kitty'
subtemplate = 'default-256'
hook = 'kitty @ set-colors -a -c $HOME/.dotfiles/theme/kitty/theme.conf'

# zathura
[[item]]
file = '$HOME/.dotfiles/theme/zathura/zathurarc'
template = 'zathura'
subtemplate = 'recolor'

# 
# # neovim
# [[item]]
# file = '$HOME/.dotfiles/config/nvim/lua/colors.lua'
# template = 'vim'
# subtemplate = 'nvim'
# start = '-- start flavours'
# end = '-- end flavours'
# # hook = ...
# # ...
