schemes = "https://github.com/Softsun2/base16-schemes-source"
# templates = "my-templates"

[[extra_scheme]]
name = "tarko"
source = "https://github.com/Softsun2/base16-tarko-scheme"

[[extra_scheme]]
name = "everforest"
source = "https://github.com/Softsun2/base16-everforest"

[[extra_scheme]]
name = "og-themes"
source = "https://github.com/Softsun2/base16-og-themes"

[[extra_template]]
name = "nvim-base16"
source = "https://github.com/Softsun2/base16-nvim-base16"

# kitty
[[item]]
file = '$HOME/.dotfiles/theme/kitty/theme.conf'
template = 'kitty'
subtemplate = 'default-256'
hook = 'kitty @ set-colors -a -c $HOME/.dotfiles/theme/kitty/theme.conf'

# zathura
[[item]]
file = '$HOME/.dotfiles/theme/zathura/zathurarc'
template = 'zathura'
subtemplate = 'recolor'

# neovim
[[item]]
file = '$HOME/.dotfiles/config/nvim/lua/colors.lua'
template = 'nvim-base16'
start = '-- start flavours'
end = '-- end flavours'
# hook = ...
