schemes = "https://github.com/Softsun2/base16-schemes-source"
# templates = "my-templates"

[[extra_scheme]]
name = "tarko"
source = "https://github.com/Softsun2/base16-tarko-scheme"

[[extra_scheme]]
name = "everforest"
source = "https://github.com/Softsun2/base16-everforest"

[[extra_scheme]]
name = "og-themes"
source = "https://github.com/Softsun2/base16-og-themes"

[[extra_scheme]]
name = "solarized"
source = "https://github.com/Softsun2/base16-solarized-scheme"

[[extra_scheme]]
name = "moonlight"
source = "https://github.com/jswinarton/base16-moonlight-scheme"

[[extra_scheme]]
name = "catpuccin"
source = "https://github.com/augustebaum/base16-catppuccin-schemes"

[[extra_scheme]]
name = "nono"
source = "https://github.com/elmotec/base16-nono-scheme"

[[extra_scheme]]
name = "paint"
source = "https://github.com/dark-beep-boop/base16-painted-scheme"

[[extra_template]]
name = "nvim-base16"
source = "https://github.com/Softsun2/base16-nvim-base16"

[[extra_template]]
name = "macos-bg"
source = "https://github.com/Softsun2/base16-macos-bg"


# kitty
[[item]]
file = '$HOME/.dotfiles/theme/kitty/theme.conf'
template = 'kitty'
subtemplate = 'default-256'
hook = 'kitty @ set-colors -a -c $HOME/.dotfiles/theme/kitty/theme.conf'

# zathura
# [[item]]
# file = '$HOME/.dotfiles/theme/zathura/zathurarc'
# template = 'zathura'
# subtemplate = 'recolor'

# neovim
[[item]]
file = '$HOME/.dotfiles/config/nvim/lua/colors.lua'
template = 'nvim-base16'
start = '-- start flavours'
end = '-- end flavours'
hook = 'reloadnvim'

# MacOS background
[[item]]
file = '$HOME/.dotfiles/theme/bg.txt'
template = 'macos-bg'
hook = 'python3 ~/personal/base-16/macos/bg-wm-hook.py'
light = false

